services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: npm run start:dev
    ports:
      - '${PORT}:${PORT}'

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  node_modules:
  postgres_data:
